# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('chain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TitleText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chain', models.TextField()),
            ],
        ),
    ]
