# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='dialoglog_text',
        ),
        migrations.AddField(
            model_name='page',
            name='char_id',
            field=models.CharField(db_index=True, default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='dialoglog',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='post_dialog_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='pre_dialog_text',
            field=models.TextField(default=''),
        ),
    ]
