# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20160110_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertext',
            name='character_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
