# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_charactertext_character_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
