# Generated by Django 2.1.2 on 2018-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_page_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
