# Generated by Django 2.1.2 on 2018-10-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20181011_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='char_id',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
