# Generated by Django 2.1.2 on 2018-10-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_auto_20181012_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterText',
        ),
        migrations.DeleteModel(
            name='GeneralText',
        ),
        migrations.DeleteModel(
            name='TitleText',
        ),
    ]
